description: Survive reboots when launching some titles

patches:
    patch1.bin:
        type: NATIVE_FIRM
        options:
            - save
        variables:
            - open  # fopen
            - rebc  # reboot_code
            - fix_
        versions:
            o3ds:
                0x5E:
                    offset: 0x08084B80
                    variables:
                        - 0x08059E48
                        - &reboot_code_o3ds 0x080FF4FC
                        - &fix_nop 0xE1A00000
                0x5C:
                    offset: 0x08084B3C
                    variables:
                        - 0x08059E34
                        - *reboot_code_o3ds
                        - *fix_nop
                0x52:
                    offset: 0x08084ACC
                    variables:
                        - 0x08059D24
                        - *reboot_code_o3ds
                        - *fix_nop
                0x50:
                    offset: 0x08084A10
                    variables:
                        - 0x08059D10
                        - *reboot_code_o3ds
                        - *fix_nop
                0x49:
                    offset: 0x080859FC
                    variables:
                        - 0x0805B180
                        - *reboot_code_o3ds
                        - *fix_nop
                0x38:
                    offset: 0x08085914
                    variables:
                        - 0x0805AF20
                        - *reboot_code_o3ds
                        - *fix_nop
                0x37:
                    offset: 0x08085894
                    variables:
                        - 0x0805AF88
                        - *reboot_code_o3ds
                        - *fix_nop
                0x30:
                    offset: 0x080855C4
                    variables:
                        - 0x0805ADA4
                        - *reboot_code_o3ds
                        - *fix_nop
                0x2A:
                    offset: 0x08085568
                    variables:
                        - 0x0805AF88
                        - *reboot_code_o3ds
                        - *fix_nop
                0x1F:
                    offset: 0x08086B64
                    variables:
                        - 0x0805CF04
                        - *reboot_code_o3ds
                        - *fix_nop
            n3ds:
                0x2F:
                    offset: 0x08084B7C
                    variables:
                        - 0x08059E44
                        - &reboot_code_n3ds 0x0817F4FC
                        - &fix_mov_r7_r8 0xE1A07008
                0x2D:
                    offset: 0x08084B3C
                    variables:
                        - 0x08059E30
                        - *reboot_code_n3ds
                        - *fix_nop
                0x21:
                    offset: 0x08084AC4
                    variables:
                        - 0x08059D20
                        - *reboot_code_n3ds
                        - *fix_nop
                0x1F:
                    offset: 0x08084A0C
                    variables:
                        - 0x08059D10
                        - *reboot_code_n3ds
                        - *fix_nop
                0x1B:
                    offset: 0x080849F0
                    variables:
                        - 0x08059D0C
                        - *reboot_code_n3ds
                        - *fix_nop
                0x0F:
                    offset: 0x08085968
                    variables:
                        - 0x0805B014
                        - *reboot_code_n3ds
                        - *fix_nop

    patch2.bin:
        type: NATIVE_FIRM
        versions:
            o3ds:
                0x5E: 0x08094220
                0x5C: 0x080941F0
                0x52: 0x080940C8
                0x50: 0x080933CC
                0x49: 0x08094454
                0x38: 0x08094200
                0x37: 0x080943A4
                0x30: 0x080940AC
                0x2A: 0x08093F28
                0x1F: 0x0809744C
            n3ds:
                0x2F: 0x08094298
                0x2D: 0x08094260
                0x21: 0x08094134
                0x1F: 0x0809343C
                0x1B: 0x08093420
                0x0F: 0x0809435C
